#!/usr/bin/env bash
# Create a file /var/run/myscript.pid containing the script PID.
# Displays "To infinity and beyond" infenatly
# Displays "I hate the kill command" if SIGTERM signal receiv
# Displays "Y U no love me?!" if SIGINT signal received
# Deletes the file /var/run/myscript.pid and terminates when
# receiving a SIGQUIT or SIGTERM signals

terminator() {
  rm /var/run/myscript.pid
  exit
}
echo "$$" > /var/run/myscript.pid

while true

do

  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT

done
