#!/usr/bin/env bash
# Displays "Best School" and "Hi" on the nineth iteration

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
	done
